### ISSUE TITLE
Ofbiz docker code for latest

### ISSUE THREAD

**Issue by sathishmtech01** [sandeepkose/OFBiz-Docker#1]
With the latest ofbiz code the docker file is not supporting..

Few changes 
Initially  no runtime() found mysql  for mysql
changed entrypoint.sh
from
sed -i "181i runtime 'mysql:mysql-connector-java:5.1.47'" build.gradle
to
sed -i "264i compile 'mysql:mysql-connector-java:5.1.47'" build.gradle

Tried 

./compose-up.sh mysql

 Configure project :
You are using one or more deprecated Asciidoctor Gradle plugin features. To help with migration run with --warning-mode=all.

> Task :compileJava UP-TO-DATE
> Task :compileGroovy UP-TO-DATE
> Task :nodeSetup UP-TO-DATE
> Task :npmSetup SKIPPED

> Task :npmInstall FAILED
env: can't execute 'node': No such file or directory

FAILURE: Build failed with an exception.

Could you please update the docker with latest

**Comment by dixitdeepak** [comment]
Hi @sandeepkose / @sathishmtech01 

You need to update msyql jar from 5.1.* to 8.0.30 or higher .Please refer  issue[1] for more detail
Also instead of `runtime` please use `runtimeOnly` to include msyql dependency.

[1]https://issues.apache.org/jira/browse/OFBIZ-12675
[2] https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-upgrading-to-8.0.html

**Comment by sathishmtech01** [comment]
Thanks @dixitdeepak
